# Generated by Django 4.0.4 on 2022-04-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiomovies',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Tv Shows', 'Tv Shows')], max_length=100),
        ),
    ]
