# Generated by Django 4.0.4 on 2022-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
