# Generated by Django 4.0.4 on 2022-07-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_blog', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='caption',
            field=models.CharField(default='', max_length=255),
        ),
    ]
