# Generated by Django 4.0.4 on 2022-07-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_blog', '0004_othervids'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuringProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='Production Videos')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OtherVids',
        ),
    ]
