# Generated by Django 4.0.4 on 2022-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_blog', '0005_duringproduction_delete_othervids'),
    ]

    operations = [
        migrations.AddField(
            model_name='duringproduction',
            name='poster',
            field=models.ImageField(default='', upload_to='Poster'),
        ),
    ]
